### ISSUE TITLE
this.props.children not rendered as expected

### ISSUE THREAD

**Issue by transedward** [devknoll/relay-nested-routes#7]
Hey, thanks for creating this library.
Recently, I tried a chat example using Relay using this library but seems no luck
I defined my routes as following
https://github.com/transedward/relay/blob/master/examples/chat/js/app.js

when go to '/', React will render `ChatApp`
https://github.com/transedward/relay/blob/master/examples/chat/js/components/ChatApp.js, 
then ThreadSection would be rendered as expected, which is good,
then seems I add `transition` in `ComponentWillMount`  to `'thread/' +currentId`,
It should render `MessageSection` for `this.props.children`
But instead, console will throw `Cannot set property 'validated' of undefined` and nothing be rendered for `this.props.children`
I print `this.props.children`, and which is as normal React Component should look like
and props got correct query result

And I can't find working example for this lib, so I sure if I'm doing anything wrong.
If you can help, I will be grateful, `clone`, `npm install` and `npm start`, then looking at console
You can see what `this.props.children` looks like
thanks for any advice and feedback in advance

**Comment by taion** [comment]
This looks like a bug in your code - https://github.com/transedward/relay/blob/044c8aba69578603c55b2500947edfb02c12f2cc/examples/chat/js/components/MessageSection.js#L29

`this.props.messages` isn't going to be defined, since that's not one of the fragments defined on your containe.

**Comment by fortruce** [comment]
You should reference `this.props.thread.messages`. Also, there are some errors in your schema in that your `typeResolver` for `nodeDefinitions` will not work with the way `database.js` is set up. None of the Threads or Messages returned by the database functions actually return instances of the types being checked for (https://github.com/transedward/relay/blob/master/examples/chat/data/schema.js#L48-L57).

You can modify the `typeResolver` to the following:

```
  (obj) => {
    console.log('type resolving');
    if (obj.id.indexOf('t_') === 0)
      return GraphQLThread;
    if (obj.id.indexOf('m_') === 0)
      return GraphQLMessage;
    if (obj.id === 'me')
      return GraphQLUser;
    return null;
  }
```

Also, GraphQL will complain if you don't supply either `first, last, or find` when querying a Connection in your query, so try `messages(first: 99999)` at https://github.com/transedward/relay/blob/master/examples/chat/js/components/MessageSection.js#L58.

Finally, you have to pass along `thread` and `viewer` to `MessageComposer` in `MessageSection`s render:

```
<MessageComposer threadID={this.props.thread.id} thread={this.props.thread} viewer={this.props.viewer} />
```

PS: you should update to Relay 0.1.1 as well.

**Comment by transedward** [comment]
many thanks, @taion @fortruce thanks for all the hard work
I'm not familiar with relay enough so making naive mistakes
now the example is working except that AddMessageMutation not optimistically update as expected
Probably not update all the relevant view as I needed
Anyone with interest can see it here: https://github.com/transedward/relay
and one with hot-reloading and source-map here: https://github.com/transedward/relay-chat
